// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"feedback/app/model/internal"
)

// Message is the golang structure for table message.
type Message internal.Message

// Fill with you ideas below.
