// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// MessageDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type MessageDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns messageColumns // Columns contains all the columns of Table that for convenient usage.
}

// MessageColumns defines and stores column names for table message.
type messageColumns struct {
	Id        string //
	Uid       string // 用户ID
	Content   string // 留言内容
	CreatedAt string // 创建时间
}

func NewMessageDao() *MessageDao {
	return &MessageDao{
		M:     g.DB("default").Model("message").Safe(),
		DB:    g.DB("default"),
		Table: "message",
		Columns: messageColumns{
			Id:        "id",
			Uid:       "uid",
			Content:   "content",
			CreatedAt: "created_at",
		},
	}
}
